name       : phonon-backend-gstreamer
version    : 4.10.0
release    : 11
source     :
    - https://download.kde.org/stable/phonon/phonon-backend-gstreamer/4.10.0/phonon-backend-gstreamer-4.10.0.tar.xz : c5871835521d015ef2ad1276b1f58340d946c2903466337f3170bac3c58d61f2
license    : LGPL-2.1
component  : multimedia.library
autodep    : false
summary    : GStreamer backend for the Qt Phonon library
description: |
    GStreamer backend for the Qt Phonon library
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5OpenGL)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(Qt5Designer)
    - pkgconfig(x11)
    - extra-cmake-modules
rundeps    :
    - gstreamer-1.0-plugins-base
    - qt5-x11extras
setup      : |
    %cmake_ninja -DPHONON_BUILD_PHONON4QT5=1 .
build      : |
    %ninja_build
install    : |
    %ninja_install
