name       : phonon-backend-gstreamer
version    : 4.9.0
release    : 6
source     :
    - http://cdn.download.kde.org/stable/phonon/phonon-backend-gstreamer/4.9.0/phonon-backend-gstreamer-4.9.0.tar.xz : cec3e5ece1261d344b68363ef0606ebf49772628ba94bb55b0c0d18773b885f1
license    : LGPL-2.1
component  : multimedia.library
autodep    : false
summary    : GStreamer backend for the Qt Phonon library
description: |
    GStreamer backend for the Qt Phonon library
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(phonon4qt5)
    - pkgconfig(Qt5OpenGL)
    - pkgconfig(Qt5X11Extras)
    - extra-cmake-modules
rundeps    :
    - gstreamer-1.0-plugins-base
    - qt5-x11extras
setup      : |
    %cmake_ninja -DPHONON_BUILD_PHONON4QT5=1 .
build      : |
    %ninja_build
install    : |
    %ninja_install
